### ISSUE TITLE
[SITE-002]: Строки, которые используем в enum или const

### ISSUE THREAD

**Issue by dHIM24** [panamera3/GostProject#10]
https://github.com/panamera3/GostProject/blob/4970619b6f5cf24558e43f53904630c50bc30f8f/GostProjectClient/src/components/GostTable/GostTable.js#L172

**Comment by dHIM24** [comment]
Все это делается с целью обеспечения единого источника истины

**Comment by panamera3** [comment]
Вынесено в отдельную переменную в коммите "fixed some issues(1)"
