### ISSUE TITLE
[SITE-002]: Рефакторинг, что-то очень страшное

### ISSUE THREAD

**Issue by dHIM24** [panamera3/GostProject#11]
https://github.com/panamera3/GostProject/blob/4970619b6f5cf24558e43f53904630c50bc30f8f/GostProjectClient/src/components/GostTable/GostTable.js#L177

**Comment by dHIM24** [comment]
двойные условные выражения недопустимы, юзай ифы или switch

**Comment by panamera3** [comment]
fixed in "fixed issues 2" commit
