### ISSUE TITLE
[SITE-005]: Хранить токен в http-only Cookie

### ISSUE THREAD

**Issue by dHIM24** [panamera3/GostProject#13]
https://github.com/panamera3/GostProject/blob/4970619b6f5cf24558e43f53904630c50bc30f8f/GostProjectClient/src/components/GostsTable/GostsTable.js#L70

ты хранишь и пробрасываешь токен в локалсторадж, в идеале если ты его сможешь на бэке в куках хранить!
я смотрел что везде используем роутеры, мб лучше хранить где нибудь в состоянии токен чем в локалке

**Comment by dHIM24** [comment]
@panamera3 , предлагаю обсудить возможность реализации, либо спрятать в состоянии

**Comment by panamera3** [comment]
fixed in commits from 26.07.2024
