### ISSUE TITLE
[SITE-001]: Очистить код от комментариев и лишних логов

### ISSUE THREAD

**Issue by dHIM24** [panamera3/GostProject#16]
https://github.com/panamera3/GostProject/blob/4970619b6f5cf24558e43f53904630c50bc30f8f/GostProjectClient/src/components/LeftColumnLogReg/LeftColumnLogReg.js#L13

А знаешь почему ты все консолишь? Нет архитектуры кода)

**Comment by dHIM24** [comment]
+ к тому же не декомпозируешь, то есть не понимаешь что у тебя принимается в этой компоненте

**Comment by dHIM24** [comment]
+ тса нет, а тс очень помогает узнать что принимает и отдает компонента

**Comment by panamera3** [comment]
Удалила лишние console.log() и комменатрии (на сколько это возможно, оставила только пару)  в коммите "fixed some issues(1)" в коммите "fixed some issues(1)"
