### ISSUE TITLE
[SITE-004]: Переиспользуемая таблица

### ISSUE THREAD

**Issue by dHIM24** [panamera3/GostProject#17]
https://github.com/panamera3/GostProject/blob/4970619b6f5cf24558e43f53904630c50bc30f8f/GostProjectClient/src/components/NotificationsTable/NotificationsTable.js#L29

Предлагаю сделать переиспользуемую таблицу, просто смотрю у тебя их несколько

**Comment by panamera3** [comment]
fixed in "fixed issues 2" commit
