### ISSUE TITLE
[SITE-001]: JS to JSX

### ISSUE THREAD

**Issue by dHIM24** [panamera3/GostProject#2]
https://github.com/panamera3/GostProject/blob/4970619b6f5cf24558e43f53904630c50bc30f8f/GostProjectClient/src/components/GostTable/GostTable.js#L1
Здесь и далее по приложению...

Все файлы должны иметь расширение JSX, это общая договоренность при использовании React
https://ru.react.js.org/docs/introducing-jsx.html

**Comment by panamera3** [comment]
fixed in "fixed issues" commit
