### ISSUE TITLE
[SITE-001]: Декомпозируем пропсы

### ISSUE THREAD

**Issue by dHIM24** [panamera3/GostProject#9]
https://github.com/panamera3/GostProject/blob/4970619b6f5cf24558e43f53904630c50bc30f8f/GostProjectClient/src/components/GostTable/GostTable.js#L12

const GostTable = ({edit, id и так далее}) => {

**Comment by dHIM24** [comment]
Здесь и далее по коду, из-за этого у тебя много логов

**Comment by panamera3** [comment]
Декомпозированы все props в коммите fixed some issueis(2)
